version: '3.2'

services:
  filebeat:
    image: devops/filebeatimage
    networks:
      - elk
      - taxcode_network
    volumes:
      - /var/lib/docker/containers:/usr/share/dockerlogs/data
      - /var/run/docker.sock
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
      - taxcode_network

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: false
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
      - taxcode_network
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elk
      - taxcode_network
    depends_on:
      - elasticsearch

  bot:
    image: service/bot:latest
    networks:
      - taxcode_network
      - elk

  taxcode:
    image: service/taxcode:latest
    ports:
    - 8080:8080
    networks:
      - taxcode_network
      - elk

  comuni:
    image: service/comuni:latest
    ports:
      - 8050:8050
    networks:
      - taxcode_network
      - elk

networks:
  elk:
    driver: bridge
  taxcode_network:
    driver: bridge

volumes:
  elasticsearch:
